#Rutas Controlador: Usuario
user:
    path: /usuario
    controller: App\Controller\UserController::index
    methods: [POST]

register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]
    
#Rutas  Controlador: Video
video:
    path: /video
    controller: App\Controller\VideoController::index
